
name: Aplication Product
description: API that allows you to manage products
version: 0.1.0
authors:
  - smc 


on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
