version: '3.8'

services:
  # Product Microservice
  ms-product:
    image: ms-product
    container_name: linktic-product-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - linktic-shared-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api-products/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  linktic-shared-network:
    external: true

